import { Header } from '@/shared/components/shared'
import type { Metadata } from 'next'
import { Suspense } from 'react'

export const metadata: Metadata = {
	title: 'Кошик',
	description: 'Generated by create next app',
}

export default function CheckoutLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<main className='min-h-screen bg-[#f4f1ee]'>
			<Suspense>
				<Header
					hasSearch={false}
					hasCart={false}
					className='border-gray-200'
				></Header>
			</Suspense>
			{children}
		</main>
	)
}
